In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("emma_original_data.csv")

In [3]:
data

,Date as of,First week,Last week,State,County name,FIPS County Code,Urban Rural Code,Deaths involving COVID-19,Deaths from All Causes
0,1/6/21,1/4/20,1/2/21,AK,Anchorage Borough,2020,Medium metro,112,"2,143"
1,1/6/21,1/4/20,1/2/21,AK,Fairbanks North Star Borough,2090,Small metro,22,509
2,1/6/21,1/4/20,1/2/21,AK,Kenai Peninsula Borough,2122,Noncore,10,358
3,1/6/21,1/4/20,1/2/21,AK,Matanuska-Susitna Borough,2170,Medium metro,12,591
4,1/6/21,1/4/20,1/2/21,AL,Autauga County,1001,Medium metro,41,488
...,...,...,...,...,...,...,...,...,...
1860,1/6/21,1/4/20,1/2/21,WY,Laramie County,56021,Small metro,53,926
1861,1/6/21,1/4/20,1/2/21,WY,Natrona County,56025,Small metro,105,993
1862,1/6/21,1/4/20,1/2/21,WY,Sheridan County,56033,Micropolitan,16,296
1863,1/6/21,1/4/20,1/2/21,WY,Sweetwater County,56037,Micropolitan,16,344
1864,1/6/21,1/4/20,1/2/21,WY,Washakie County,56043,Noncore,13,84

In [4]:
import numpy as np

In [5]:
to_drop = ['Date as of',
          'First week',
          'Last week']
data.drop(to_drop, inplace=True, axis=1)

In [6]:
data

,State,County name,FIPS County Code,Urban Rural Code,Deaths involving COVID-19,Deaths from All Causes
0,AK,Anchorage Borough,2020,Medium metro,112,"2,143"
1,AK,Fairbanks North Star Borough,2090,Small metro,22,509
2,AK,Kenai Peninsula Borough,2122,Noncore,10,358
3,AK,Matanuska-Susitna Borough,2170,Medium metro,12,591
4,AL,Autauga County,1001,Medium metro,41,488
...,...,...,...,...,...,...
1860,WY,Laramie County,56021,Small metro,53,926
1861,WY,Natrona County,56025,Small metro,105,993
1862,WY,Sheridan County,56033,Micropolitan,16,296
1863,WY,Sweetwater County,56037,Micropolitan,16,344
1864,WY,Washakie County,56043,Noncore,13,84

In [7]:
data = data[data.State.isin(['CA','WA','OR'])]

In [8]:
data

,State,County name,FIPS County Code,Urban Rural Code,Deaths involving COVID-19,Deaths from All Causes
111,CA,Alameda County,6001,Large central metro,573,"10,908"
112,CA,Alpine County,6003,NaN,0,NaN
113,CA,Amador County,6005,Noncore,31,415
114,CA,Butte County,6007,Small metro,101,"2,313"
115,CA,Calaveras County,6009,Noncore,12,385
...,...,...,...,...,...,...
1778,WA,Wahkiakum County,53069,NaN,0,NaN
1779,WA,Walla Walla County,53071,Small metro,38,651
1780,WA,Whatcom County,53073,Small metro,63,"1,881"
1781,WA,Whitman County,53075,Micropolitan,21,269
1782,WA,Yakima County,53077,Small metro,266,"2,239"

In [9]:
data['Urban Rural Code'].fillna('Not Available', inplace = True)

/Users/emmali/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [10]:
data

,State,County name,FIPS County Code,Urban Rural Code,Deaths involving COVID-19,Deaths from All Causes
111,CA,Alameda County,6001,Large central metro,573,"10,908"
112,CA,Alpine County,6003,Not Available,0,NaN
113,CA,Amador County,6005,Noncore,31,415
114,CA,Butte County,6007,Small metro,101,"2,313"
115,CA,Calaveras County,6009,Noncore,12,385
...,...,...,...,...,...,...
1778,WA,Wahkiakum County,53069,Not Available,0,NaN
1779,WA,Walla Walla County,53071,Small metro,38,651
1780,WA,Whatcom County,53073,Small metro,63,"1,881"
1781,WA,Whitman County,53075,Micropolitan,21,269
1782,WA,Yakima County,53077,Small metro,266,"2,239"

In [11]:
data['Deaths from All Causes'].fillna(0, inplace = True)

/Users/emmali/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [12]:
data

,State,County name,FIPS County Code,Urban Rural Code,Deaths involving COVID-19,Deaths from All Causes
111,CA,Alameda County,6001,Large central metro,573,"10,908"
112,CA,Alpine County,6003,Not Available,0,0
113,CA,Amador County,6005,Noncore,31,415
114,CA,Butte County,6007,Small metro,101,"2,313"
115,CA,Calaveras County,6009,Noncore,12,385
...,...,...,...,...,...,...
1778,WA,Wahkiakum County,53069,Not Available,0,0
1779,WA,Walla Walla County,53071,Small metro,38,651
1780,WA,Whatcom County,53073,Small metro,63,"1,881"
1781,WA,Whitman County,53075,Micropolitan,21,269
1782,WA,Yakima County,53077,Small metro,266,"2,239"

In [13]:
data_new = data.rename(columns={'County name':'County'})

In [14]:
data_new

,State,County,FIPS County Code,Urban Rural Code,Deaths involving COVID-19,Deaths from All Causes
111,CA,Alameda County,6001,Large central metro,573,"10,908"
112,CA,Alpine County,6003,Not Available,0,0
113,CA,Amador County,6005,Noncore,31,415
114,CA,Butte County,6007,Small metro,101,"2,313"
115,CA,Calaveras County,6009,Noncore,12,385
...,...,...,...,...,...,...
1778,WA,Wahkiakum County,53069,Not Available,0,0
1779,WA,Walla Walla County,53071,Small metro,38,651
1780,WA,Whatcom County,53073,Small metro,63,"1,881"
1781,WA,Whitman County,53075,Micropolitan,21,269
1782,WA,Yakima County,53077,Small metro,266,"2,239"

In [15]:
data_new = data.rename(columns={'FIPS County Code':'FIPS_code'})

In [16]:
data_new = data.rename(columns={'Urban Rural Code':'Urban_Rural_Code'})

In [17]:
data_new = data.rename(columns={'Death involving COVID-19':'Deaths_COVID'})

In [18]:
data_new = data.rename(columns={'Death from All Causes':'Deaths_total'})

In [19]:
data_rename = data
data_rename =data.rename(columns={'County name':'County','FIPS County Code':'FIPS_code','Urban Rural Code':'Urban_Rural_Code','Deaths involving COVID-19':'Deaths_COVID','Deaths from All Causes':'Deaths_total'},inplace=True)

/Users/emmali/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [20]:
data_rename

In [21]:
data

,State,County,FIPS_code,Urban_Rural_Code,Deaths_COVID,Deaths_total
111,CA,Alameda County,6001,Large central metro,573,"10,908"
112,CA,Alpine County,6003,Not Available,0,0
113,CA,Amador County,6005,Noncore,31,415
114,CA,Butte County,6007,Small metro,101,"2,313"
115,CA,Calaveras County,6009,Noncore,12,385
...,...,...,...,...,...,...
1778,WA,Wahkiakum County,53069,Not Available,0,0
1779,WA,Walla Walla County,53071,Small metro,38,651
1780,WA,Whatcom County,53073,Small metro,63,"1,881"
1781,WA,Whitman County,53075,Micropolitan,21,269
1782,WA,Yakima County,53077,Small metro,266,"2,239"

In [22]:
df.to_csv('133_county.csv',header = True)

NameError: name 'df' is not defined

In [23]:
data.to_csv('133_county.csv',header = True)

In [24]:
data

,State,County,FIPS_code,Urban_Rural_Code,Deaths_COVID,Deaths_total
111,CA,Alameda County,6001,Large central metro,573,"10,908"
112,CA,Alpine County,6003,Not Available,0,0
113,CA,Amador County,6005,Noncore,31,415
114,CA,Butte County,6007,Small metro,101,"2,313"
115,CA,Calaveras County,6009,Noncore,12,385
...,...,...,...,...,...,...
1778,WA,Wahkiakum County,53069,Not Available,0,0
1779,WA,Walla Walla County,53071,Small metro,38,651
1780,WA,Whatcom County,53073,Small metro,63,"1,881"
1781,WA,Whitman County,53075,Micropolitan,21,269
1782,WA,Yakima County,53077,Small metro,266,"2,239"

In [25]:
data

,State,County,FIPS_code,Urban_Rural_Code,Deaths_COVID,Deaths_total
111,CA,Alameda County,6001,Large central metro,573,"10,908"
112,CA,Alpine County,6003,Not Available,0,0
113,CA,Amador County,6005,Noncore,31,415
114,CA,Butte County,6007,Small metro,101,"2,313"
115,CA,Calaveras County,6009,Noncore,12,385
...,...,...,...,...,...,...
1778,WA,Wahkiakum County,53069,Not Available,0,0
1779,WA,Walla Walla County,53071,Small metro,38,651
1780,WA,Whatcom County,53073,Small metro,63,"1,881"
1781,WA,Whitman County,53075,Micropolitan,21,269
1782,WA,Yakima County,53077,Small metro,266,"2,239"

In [26]:
import pandas as pd

In [27]:
data

,State,County,FIPS_code,Urban_Rural_Code,Deaths_COVID,Deaths_total
111,CA,Alameda County,6001,Large central metro,573,"10,908"
112,CA,Alpine County,6003,Not Available,0,0
113,CA,Amador County,6005,Noncore,31,415
114,CA,Butte County,6007,Small metro,101,"2,313"
115,CA,Calaveras County,6009,Noncore,12,385
...,...,...,...,...,...,...
1778,WA,Wahkiakum County,53069,Not Available,0,0
1779,WA,Walla Walla County,53071,Small metro,38,651
1780,WA,Whatcom County,53073,Small metro,63,"1,881"
1781,WA,Whitman County,53075,Micropolitan,21,269
1782,WA,Yakima County,53077,Small metro,266,"2,239"

In [28]:
data = pd.read_csv("133_county.csv")

In [29]:
data

,Unnamed: 0,State,County,FIPS_code,Urban_Rural_Code,Deaths_COVID,Deaths_total
0,111,CA,Alameda County,6001,Large central metro,573,"10,908"
1,112,CA,Alpine County,6003,Not Available,0,0
2,113,CA,Amador County,6005,Noncore,31,415
3,114,CA,Butte County,6007,Small metro,101,"2,313"
4,115,CA,Calaveras County,6009,Noncore,12,385
...,...,...,...,...,...,...,...
128,1778,WA,Wahkiakum County,53069,Not Available,0,0
129,1779,WA,Walla Walla County,53071,Small metro,38,651
130,1780,WA,Whatcom County,53073,Small metro,63,"1,881"
131,1781,WA,Whitman County,53075,Micropolitan,21,269
132,1782,WA,Yakima County,53077,Small metro,266,"2,239"

In [30]:
to_drop = ['FIPS_code']
data.drop(to_drop, inplace=True, axis=1)

In [31]:
data

,Unnamed: 0,State,County,Urban_Rural_Code,Deaths_COVID,Deaths_total
0,111,CA,Alameda County,Large central metro,573,"10,908"
1,112,CA,Alpine County,Not Available,0,0
2,113,CA,Amador County,Noncore,31,415
3,114,CA,Butte County,Small metro,101,"2,313"
4,115,CA,Calaveras County,Noncore,12,385
...,...,...,...,...,...,...
128,1778,WA,Wahkiakum County,Not Available,0,0
129,1779,WA,Walla Walla County,Small metro,38,651
130,1780,WA,Whatcom County,Small metro,63,"1,881"
131,1781,WA,Whitman County,Micropolitan,21,269
132,1782,WA,Yakima County,Small metro,266,"2,239"

In [32]:
data.to_csv('133_county_new.csv',header = True)

In [33]:
import pandas as pd

In [34]:
data = pd.read_csv("133_county_new.csv")

In [35]:
data

,Unnamed: 0,Unnamed: 0.1,State,County,Urban_Rural_Code,Deaths_COVID,Deaths_total
0,0,111,CA,Alameda County,Large central metro,573,"10,908"
1,1,112,CA,Alpine County,Not Available,0,0
2,2,113,CA,Amador County,Noncore,31,415
3,3,114,CA,Butte County,Small metro,101,"2,313"
4,4,115,CA,Calaveras County,Noncore,12,385
...,...,...,...,...,...,...,...
128,128,1778,WA,Wahkiakum County,Not Available,0,0
129,129,1779,WA,Walla Walla County,Small metro,38,651
130,130,1780,WA,Whatcom County,Small metro,63,"1,881"
131,131,1781,WA,Whitman County,Micropolitan,21,269
132,132,1782,WA,Yakima County,Small metro,266,"2,239"

In [36]:
to_drop = ['Unnamed: 0.1',
          'Unnamed: 0']
data.drop(to_drop, inplace=True, axis=1)

In [37]:
data

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [38]:
data

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [39]:
data

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [40]:
data = pd.read_csv("133_county_data.csv")

FileNotFoundError: [Errno 2] No such file or directory: '133_county_data.csv'

In [41]:
data.to_csv('133_county_data.csv',header = True)

In [42]:
data

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [43]:
data = pd.read_csv("133_county_data.csv")

In [44]:
import pandas as pd

In [45]:
data = pd.read_csv("133_county_data.csv")

In [46]:
data

,Unnamed: 0,State,County,Urban_Rural_Code,Deaths_COVID,Deaths_total
0,0,CA,Alameda County,Large central metro,573,"10,908"
1,1,CA,Alpine County,Not Available,0,0
2,2,CA,Amador County,Noncore,31,415
3,3,CA,Butte County,Small metro,101,"2,313"
4,4,CA,Calaveras County,Noncore,12,385
...,...,...,...,...,...,...
128,128,WA,Wahkiakum County,Not Available,0,0
129,129,WA,Walla Walla County,Small metro,38,651
130,130,WA,Whatcom County,Small metro,63,"1,881"
131,131,WA,Whitman County,Micropolitan,21,269
132,132,WA,Yakima County,Small metro,266,"2,239"

In [47]:
data.describe

<bound method NDFrame.describe of      Unnamed: 0 State              County     Urban_Rural_Code Deaths_COVID  \
0             0    CA      Alameda County  Large central metro          573
1             1    CA       Alpine County        Not Available            0
2             2    CA       Amador County              Noncore           31
3             3    CA        Butte County          Small metro          101
4             4    CA    Calaveras County              Noncore           12
..          ...   ...                 ...                  ...          ...
128         128    WA    Wahkiakum County        Not Available            0
129         129    WA  Walla Walla County          Small metro           38
130         130    WA      Whatcom County          Small metro           63
131         131    WA      Whitman County         Micropolitan           21
132         132    WA       Yakima County          Small metro          266

    Deaths_total
0         10,908
1              0
2            415
3          2,313
4            385
..           ...
128            0
129          651
130        1,881
131          269
132        2,239

[133 rows x 6 columns]>

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        133 non-null    int64
 1   State             133 non-null    object
 2   County            133 non-null    object
 3   Urban_Rural_Code  133 non-null    object
 4   Deaths_COVID      133 non-null    object
 5   Deaths_total      133 non-null    object
dtypes: int64(1), object(5)
memory usage: 6.4+ KB

In [49]:
data

,Unnamed: 0,State,County,Urban_Rural_Code,Deaths_COVID,Deaths_total
0,0,CA,Alameda County,Large central metro,573,"10,908"
1,1,CA,Alpine County,Not Available,0,0
2,2,CA,Amador County,Noncore,31,415
3,3,CA,Butte County,Small metro,101,"2,313"
4,4,CA,Calaveras County,Noncore,12,385
...,...,...,...,...,...,...
128,128,WA,Wahkiakum County,Not Available,0,0
129,129,WA,Walla Walla County,Small metro,38,651
130,130,WA,Whatcom County,Small metro,63,"1,881"
131,131,WA,Whitman County,Micropolitan,21,269
132,132,WA,Yakima County,Small metro,266,"2,239"

In [50]:
to_drop = ['Unnamed: 0']
data.drop(to_drop, inplace=True, axis=1)

In [51]:
data

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             133 non-null    object
 1   County            133 non-null    object
 2   Urban_Rural_Code  133 non-null    object
 3   Deaths_COVID      133 non-null    object
 4   Deaths_total      133 non-null    object
dtypes: object(5)
memory usage: 5.3+ KB

In [53]:
data[data.iloc[:,3:].isnull().any(axis=1)]

Empty DataFrame
Columns: [State, County, Urban_Rural_Code, Deaths_COVID, Deaths_total]
Index: []

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             133 non-null    object
 1   County            133 non-null    object
 2   Urban_Rural_Code  133 non-null    object
 3   Deaths_COVID      133 non-null    object
 4   Deaths_total      133 non-null    object
dtypes: object(5)
memory usage: 5.3+ KB

In [55]:
data

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [56]:
data_change = data.copy()

In [57]:
data_change['State','County','Urban_Rural_Code'] = data_change['State','County','Urban_Rural_Code'].astype('category')

KeyError: ('State', 'County', 'Urban_Rural_Code')

In [58]:
data_change

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [59]:
data_change[State,County,Urban_Rural_Code] = data_change[State,County,Urban_Rural_Code'].astype('category')

SyntaxError: invalid syntax (<ipython-input-59-2fac3f299e77>, line 1)

In [60]:
data_change

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [61]:
data_change['Deaths_COVID'] = data_change.Death_COVID.covert_objects(covert_numeric=True)

AttributeError: 'DataFrame' object has no attribute 'Death_COVID'

In [62]:
data_change

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [63]:
data_change.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             133 non-null    object
 1   County            133 non-null    object
 2   Urban_Rural_Code  133 non-null    object
 3   Deaths_COVID      133 non-null    object
 4   Deaths_total      133 non-null    object
dtypes: object(5)
memory usage: 5.3+ KB

In [64]:
data_change["Deaths_COVID"] = pd.to_numeric(data_change.Deaths_COVID, errors='coerce')

In [65]:
data_change

    State              County     Urban_Rural_Code  Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro         573.0       10,908
1      CA       Alpine County        Not Available           0.0            0
2      CA       Amador County              Noncore          31.0          415
3      CA        Butte County          Small metro         101.0        2,313
4      CA    Calaveras County              Noncore          12.0          385
..    ...                 ...                  ...           ...          ...
128    WA    Wahkiakum County        Not Available           0.0            0
129    WA  Walla Walla County          Small metro          38.0          651
130    WA      Whatcom County          Small metro          63.0        1,881
131    WA      Whitman County         Micropolitan          21.0          269
132    WA       Yakima County          Small metro         266.0        2,239

[133 rows x 5 columns]

In [66]:
data_change.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             133 non-null    object
 1   County            133 non-null    object
 2   Urban_Rural_Code  133 non-null    object
 3   Deaths_COVID      128 non-null    float64
 4   Deaths_total      133 non-null    object
dtypes: float64(1), object(4)
memory usage: 5.3+ KB

In [67]:
data_change

    State              County     Urban_Rural_Code  Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro         573.0       10,908
1      CA       Alpine County        Not Available           0.0            0
2      CA       Amador County              Noncore          31.0          415
3      CA        Butte County          Small metro         101.0        2,313
4      CA    Calaveras County              Noncore          12.0          385
..    ...                 ...                  ...           ...          ...
128    WA    Wahkiakum County        Not Available           0.0            0
129    WA  Walla Walla County          Small metro          38.0          651
130    WA      Whatcom County          Small metro          63.0        1,881
131    WA      Whitman County         Micropolitan          21.0          269
132    WA       Yakima County          Small metro         266.0        2,239

[133 rows x 5 columns]

In [68]:
data

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [69]:
data_change2 = data.copy()

In [70]:
data_change2

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [71]:
data_change2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             133 non-null    object
 1   County            133 non-null    object
 2   Urban_Rural_Code  133 non-null    object
 3   Deaths_COVID      133 non-null    object
 4   Deaths_total      133 non-null    object
dtypes: object(5)
memory usage: 5.3+ KB

In [72]:
data_change2["Deaths_COVID"] = pd.to_numeric(data_change2.Deaths_COVID)

ValueError: Unable to parse string "8,034" at position 18

In [73]:
data_change2["Deaths_total"] = pd.to_numeric(data_change2.Deaths_total)

ValueError: Unable to parse string "10,908" at position 0

In [74]:
data_change2

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [75]:
data_change2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             133 non-null    object
 1   County            133 non-null    object
 2   Urban_Rural_Code  133 non-null    object
 3   Deaths_COVID      133 non-null    object
 4   Deaths_total      133 non-null    object
dtypes: object(5)
memory usage: 5.3+ KB

In [76]:
int(data_change2.replace(',',''))

TypeError: int() argument must be a string, a bytes-like object or a number, not 'DataFrame'

In [77]:
data_change3 = data.copy()

In [78]:
data_change3

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [79]:
int(data_change3.replace(',','')

SyntaxError: unexpected EOF while parsing (<ipython-input-79-d2212db2c9d8>, line 1)

In [80]:
import pandas as pd

In [81]:
data = pd.read_csv("133_county_data.csv")

In [82]:
data

,Unnamed: 0,State,County,Urban_Rural_Code,Deaths_COVID,Deaths_total
0,0,CA,Alameda County,Large central metro,573,"10,908"
1,1,CA,Alpine County,Not Available,0,0
2,2,CA,Amador County,Noncore,31,415
3,3,CA,Butte County,Small metro,101,"2,313"
4,4,CA,Calaveras County,Noncore,12,385
...,...,...,...,...,...,...
128,128,WA,Wahkiakum County,Not Available,0,0
129,129,WA,Walla Walla County,Small metro,38,651
130,130,WA,Whatcom County,Small metro,63,"1,881"
131,131,WA,Whitman County,Micropolitan,21,269
132,132,WA,Yakima County,Small metro,266,"2,239"

In [83]:
to_drop = ['Unnamed: 0']
data.drop(to_drop, inplace=True, axis=1)

In [84]:
data

    State              County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda County  Large central metro          573       10,908
1      CA       Alpine County        Not Available            0            0
2      CA       Amador County              Noncore           31          415
3      CA        Butte County          Small metro          101        2,313
4      CA    Calaveras County              Noncore           12          385
..    ...                 ...                  ...          ...          ...
128    WA    Wahkiakum County        Not Available            0            0
129    WA  Walla Walla County          Small metro           38          651
130    WA      Whatcom County          Small metro           63        1,881
131    WA      Whitman County         Micropolitan           21          269
132    WA       Yakima County          Small metro          266        2,239

[133 rows x 5 columns]

In [85]:
data['County'] = data['County'].str.replace('County', '')

In [86]:
data

    State        County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda   Large central metro          573       10,908
1      CA       Alpine         Not Available            0            0
2      CA       Amador               Noncore           31          415
3      CA        Butte           Small metro          101        2,313
4      CA    Calaveras               Noncore           12          385
..    ...           ...                  ...          ...          ...
128    WA    Wahkiakum         Not Available            0            0
129    WA  Walla Walla           Small metro           38          651
130    WA      Whatcom           Small metro           63        1,881
131    WA      Whitman          Micropolitan           21          269
132    WA       Yakima           Small metro          266        2,239

[133 rows x 5 columns]

In [87]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             133 non-null    object
 1   County            133 non-null    object
 2   Urban_Rural_Code  133 non-null    object
 3   Deaths_COVID      133 non-null    object
 4   Deaths_total      133 non-null    object
dtypes: object(5)
memory usage: 5.3+ KB

In [88]:
data['Urban_Rural_Code'] = data['Urban_Rural_Code'].str.replace('Not Available', 'NaN')

In [89]:
data

    State        County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda   Large central metro          573       10,908
1      CA       Alpine                   NaN            0            0
2      CA       Amador               Noncore           31          415
3      CA        Butte           Small metro          101        2,313
4      CA    Calaveras               Noncore           12          385
..    ...           ...                  ...          ...          ...
128    WA    Wahkiakum                   NaN            0            0
129    WA  Walla Walla           Small metro           38          651
130    WA      Whatcom           Small metro           63        1,881
131    WA      Whitman          Micropolitan           21          269
132    WA       Yakima           Small metro          266        2,239

[133 rows x 5 columns]

In [2]:
data.to_csv('emma_data_COVID_death.csv',header=True, index=False)

NameError: name 'data' is not defined

In [5]:
import pandas as pd
data = pd.read_csv("emma_data_COVID_death.csv")

In [6]:
data

,Unnamed: 0,State,County,Urban_Rural_Code,Deaths_COVID,Deaths_total
0,0,CA,Alameda,Large central metro,573,"10,908"
1,1,CA,Alpine,NaN,0,0
2,2,CA,Amador,Noncore,31,415
3,3,CA,Butte,Small metro,101,"2,313"
4,4,CA,Calaveras,Noncore,12,385
...,...,...,...,...,...,...
128,128,WA,Wahkiakum,NaN,0,0
129,129,WA,Walla Walla,Small metro,38,651
130,130,WA,Whatcom,Small metro,63,"1,881"
131,131,WA,Whitman,Micropolitan,21,269
132,132,WA,Yakima,Small metro,266,"2,239"

In [7]:
to_drop = ['Unnamed: 0']
data.drop(to_drop, inplace=True, axis=1)

In [8]:
data

    State        County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda   Large central metro          573       10,908
1      CA       Alpine                   NaN            0            0
2      CA       Amador               Noncore           31          415
3      CA        Butte           Small metro          101        2,313
4      CA    Calaveras               Noncore           12          385
..    ...           ...                  ...          ...          ...
128    WA    Wahkiakum                   NaN            0            0
129    WA  Walla Walla           Small metro           38          651
130    WA      Whatcom           Small metro           63        1,881
131    WA      Whitman          Micropolitan           21          269
132    WA       Yakima           Small metro          266        2,239

[133 rows x 5 columns]

In [9]:
data['County'] = data['County'].str.strip()

In [10]:
data

    State       County     Urban_Rural_Code Deaths_COVID Deaths_total
0      CA      Alameda  Large central metro          573       10,908
1      CA       Alpine                  NaN            0            0
2      CA       Amador              Noncore           31          415
3      CA        Butte          Small metro          101        2,313
4      CA    Calaveras              Noncore           12          385
..    ...          ...                  ...          ...          ...
128    WA    Wahkiakum                  NaN            0            0
129    WA  Walla Walla          Small metro           38          651
130    WA      Whatcom          Small metro           63        1,881
131    WA      Whitman         Micropolitan           21          269
132    WA       Yakima          Small metro          266        2,239

[133 rows x 5 columns]

In [11]:
data.to_csv('emma_data.csv',header=True, index=False)